<?php

namespace Models;

use App\Models\City;
use App\Models\Company;
use App\Models\Job;
use App\Models\Type;
use Tests\TestCase;

class CityTest extends TestCase
{

    protected string $table;

    protected function setUp(): void
    {
        $this->table = 'cities';
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    /**
     * Test factory is working
     *
     * @test
     */
    public function it_can_create()
    {
       City::factory()->create();

        $this->assertDatabaseCount($this->table, 1);
    }

    /**
     * Test company relation
     *
     * @test
     */
    public function a_city_can_have_many_companies()
    {
        $city = City::factory()->create();
        Company::factory()->forCity($city)->count($count = 5)->create();

        $this->assertEquals($count, $city->companies->count());
    }

    /**
     * Test type relation
     *
     * @test
     */
    public function a_job_has_one_type()
    {
        $type = Type::factory()->create();

        $job = Job::factory()->forType($type)->create();

        $this->assertInstanceOf(Type::class, $job->type);
    }
}
