<?php

namespace Models;

use App\Models\City;
use App\Models\Company;
use App\Models\Job;
use App\Models\Type;
use Tests\TestCase;

class CompanyTest extends TestCase
{

    protected string $table;

    protected function setUp(): void
    {
        $this->table = 'companies';
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    /**
     * Test factory is working
     *
     * @test
     */
    public function it_can_create()
    {
       Company::factory()->create();

        $this->assertDatabaseCount($this->table, 1);
    }

    /**
     * Test jobs relation
     *
     * @test
     */
    public function a_company_can_have_many_jobs()
    {
        $count = 5;

        $companyOne = Company::factory()->create();
        $companyTwo = Company::factory()->create();
        Job::factory()->count($count)->forCompany($companyOne)->create();

        Job::factory()->count(3)->forCompany($companyTwo)->create();

        $this->assertEquals($count, $companyOne->jobs->count());
    }

    /**
     * Test type relation
     *
     * @test
     */
    public function a_company_belongs_to_a_city()
    {
        $company = Company::factory()->create();

        $this->assertInstanceOf(City::class, $company->city);
    }
}
