<?php

namespace Models;

use App\Models\Company;
use App\Models\Job;
use App\Models\Type;
use Tests\TestCase;

class TypeTest extends TestCase
{

    protected string $table;

    protected function setUp(): void
    {
        $this->table = 'types';
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    /**
     * Test factory is working
     *
     * @test
     */
    public function it_can_create()
    {
       Type::factory()->create();

        $this->assertDatabaseCount($this->table, 1);
    }

    /**
     * Test job relation
     *
     * @test
     */
    public function a_type_has_many_jobs()
    {
        $type = Type::factory()->create();
        Job::factory()->count($count = 5)->forType($type)->create();

        $this->assertEquals($count, $type->jobs->count());
    }
}
